import { useState } from 'react';
import { Save, ArrowRight, Info, Coffee, ChevronDown, FileText, FileSpreadsheet, Image, MessageCircle, Mail, Code, Printer, Share2 } from 'lucide-react';
import { useTimetable } from '../store/TimetableContext';
import { useToast } from './Toast';
import type { TimingMode, ClassGroup, TimeSlot } from '../types';

export default function TimingArchitect() {
  const { state, dispatch } = useTimetable();
  const { toast } = useToast();
  
  const [activeGroup, setActiveGroup] = useState<ClassGroup>('VI-X');
  const [activeMode, setActiveMode] = useState<TimingMode>('Official');
  const [showExportMenu, setShowExportMenu] = useState(false);
  
  // Local state for editing
  const [editingSlots, setEditingSlots] = useState<TimeSlot[]>(
    JSON.parse(JSON.stringify(state.timeSlots[activeGroup][activeMode]))
  );

  const handleShare = (via: 'whatsapp' | 'email' | 'clipboard') => {
    const text = `⏰ *${state.schoolSettings.organizationName} - Time Schedule*\n` +
      `📌 Grade ${activeGroup} (${activeMode} Preset)\n\n` +
      editingSlots.map(s => {
        const type = s.isBreak ? '☕ BREAK' : `📖 PERIOD ${s.name}`;
        return `${type}: ${s.startTime} - ${s.endTime} (${getDuration(s.startTime, s.endTime)} min)`;
      }).join('\n') +
      `\n\n_Generated by RoutinePro_`;

    if (via === 'clipboard') {
      navigator.clipboard.writeText(text).then(() => {
        toast('success', 'Copied to Clipboard', 'The schedule has been formatted and copied.');
      });
    } else if (via === 'whatsapp') {
      window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
    } else if (via === 'email') {
      window.location.href = `mailto:?subject=School Time Schedule&body=${encodeURIComponent(text)}`;
    }
    setShowExportMenu(false);
  };

  const handleExportJSON = () => {
    const data = JSON.stringify(editingSlots, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `schedule_${activeGroup}_${activeMode}.json`;
    a.click();
    setShowExportMenu(false);
    toast('info', 'JSON Exported', 'Schedule data has been downloaded.');
  };

  const handleShareAll = () => {
    const groups: ClassGroup[] = ['VI-X', 'XI-XII'];
    let text = `🏫 *${state.schoolSettings.organizationName} - COMPLETE MASTER TIMELINE*\n` +
               `🗓️ Mode: ${activeMode}\n\n`;

    groups.forEach(group => {
      const slots = state.timeSlots[group][activeMode];
      text += `---------- GRADE ${group} ----------\n`;
      text += slots.map(s => {
        return `${s.isBreak ? '☕ BREAK' : '📖 P' + s.name}: ${s.startTime} - ${s.endTime}`;
      }).join('\n') + '\n\n';
    });

    text += `_RoutinePro | Institutional Management_`;
    navigator.clipboard.writeText(text).then(() => {
      toast('success', 'Master Copy Ready', 'Institutional timeline for all grades has been copied.');
    });
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const groups: ClassGroup[] = ['VI-X', 'XI-XII'];
    
    const html = `
      <html>
        <head>
          <title>${state.schoolSettings.organizationName} - Timing Framework</title>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet">
          <style>
            @page { size: A4; margin: 15mm; }
            body { font-family: 'Inter', sans-serif; color: #1e293b; background: white; margin: 0; padding: 0; }
            .official-header { text-align: center; padding-bottom: 20px; border-bottom: 3px solid #000; margin-bottom: 40px; }
            .school-name { font-size: 32px; font-weight: 900; text-transform: uppercase; margin: 0; color: #0f172a; letter-spacing: -0.02em; }
            .tagline { font-size: 14px; font-weight: 700; color: #475569; margin: 5px 0 0; text-transform: uppercase; letter-spacing: 0.1em; }
            
            .group-block { margin-bottom: 50px; break-inside: avoid; }
            .group-header { background: #f8fafc; border: 1px solid #e2e8f0; padding: 12px; text-align: center; font-size: 14px; font-weight: 900; text-transform: uppercase; letter-spacing: 0.2em; color: #334155; margin-bottom: 0; }
            
            table { width: 100%; border-collapse: collapse; border: 1px solid #e2e8f0; }
            th { border: 1px solid #e2e8f0; padding: 12px 15px; text-align: left; font-size: 11px; font-weight: 900; text-transform: uppercase; color: #64748b; background: white; }
            td { border: 1px solid #e2e8f0; padding: 12px 15px; text-align: left; font-size: 13px; font-weight: 700; color: #0f172a; }
            
            .is-break { background-color: #fff1f2; color: #e11d48; }
            .is-break td { color: #e11d48; }
            .span-col { color: #64748b; font-weight: 400; }
            .is-break .span-col { color: #e11d48; font-weight: 900; }
            
            .footer { margin-top: 40px; text-align: center; font-size: 10px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }
          </style>
        </head>
        <body>
          <div class="official-header">
            <h1 class="school-name">${state.schoolSettings.organizationName}</h1>
            <p class="tagline">Institutional Timing Framework — ${activeMode} Mode</p>
          </div>
          
          ${groups.map(group => {
            const slots = state.timeSlots[group][activeMode];
            return `
              <div class="group-block">
                <div class="group-header">Grade ${group}</div>
                <table>
                  <thead>
                    <tr>
                      <th style="width: 25%">Period</th>
                      <th style="width: 25%">Start</th>
                      <th style="width: 25%">End</th>
                      <th style="width: 25%">Span</th>
                    </tr>
                  </thead>
                  <tbody>
                    ${slots.map(s => `
                      <tr class="${s.isBreak ? 'is-break' : ''}">
                        <td>${s.isBreak ? 'BREAK' : 'P' + s.name}</td>
                        <td>${s.startTime}</td>
                        <td>${s.endTime}</td>
                        <td class="span-col">${getDuration(s.startTime, s.endTime)}m</td>
                      </tr>
                    `).join('')}
                  </tbody>
                </table>
              </div>
            `;
          }).join('')}

          <div class="footer">
            Generated via RoutinePro Enterprise | Academic Session ${state.academicSession} | Official Record
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `;
    printWindow.document.write(html);
    printWindow.document.close();
  };

  // Calculate duration in minutes between two "HH:mm" strings
  const getDuration = (start: string, end: string) => {
    const [h1, m1] = start.split(':').map(Number);
    const [h2, m2] = end.split(':').map(Number);
    return (h2 * 60 + m2) - (h1 * 60 + m1);
  };

  const handleTabChange = (group: ClassGroup, mode: TimingMode) => {
    setActiveGroup(group);
    setActiveMode(mode);
    setEditingSlots(JSON.parse(JSON.stringify(state.timeSlots[group][mode])));
  };

  const handleSlotChange = (index: number, field: keyof TimeSlot, value: string) => {
    const newSlots = [...editingSlots];
    const oldVal = newSlots[index][field];
    newSlots[index] = { ...newSlots[index], [field]: value };

    // Auto-propagate: If end time changed, update next slot's start time if it matches old end time
    if (field === 'endTime' && index < newSlots.length - 1) {
      if (newSlots[index + 1].startTime === oldVal) {
        newSlots[index + 1].startTime = value;
      }
    }

    setEditingSlots(newSlots);
  };

  const handleDurationChange = (index: number, minutes: number) => {
    if (isNaN(minutes)) return;
    const newSlots = [...editingSlots];
    const slot = newSlots[index];
    const [h, m] = slot.startTime.split(':').map(Number);
    let total = h * 60 + m + minutes;
    
    const nh = Math.floor(total / 60) % 24;
    const nm = total % 60;
    const newEndTime = `${nh.toString().padStart(2, '0')}:${nm.toString().padStart(2, '0')}`;
    
    const oldEndTime = slot.endTime;
    newSlots[index] = { ...slot, endTime: newEndTime };

    // Auto-propagate to next slot's start time
    if (index < newSlots.length - 1 && newSlots[index + 1].startTime === oldEndTime) {
      newSlots[index + 1].startTime = newEndTime;
    }

    setEditingSlots(newSlots);
  };

  const shiftAll = (minutes: number) => {
    const shiftTime = (timeStr: string) => {
      const [h, m] = timeStr.split(':').map(Number);
      let total = h * 60 + m + minutes;
      if (total < 0) total += 1440;
      total %= 1440;
      const nh = Math.floor(total / 60);
      const nm = total % 60;
      return `${nh.toString().padStart(2, '0')}:${nm.toString().padStart(2, '0')}`;
    };

    setEditingSlots(editingSlots.map(s => ({
      ...s,
      startTime: shiftTime(s.startTime),
      endTime: shiftTime(s.endTime)
    })));
    toast('info', 'Schedule Shifted', `All slots moved by ${minutes} minutes.`);
  };

  const saveSettings = () => {
    dispatch({ 
      type: 'UPDATE_TIME_SLOTS', 
      payload: { group: activeGroup, mode: activeMode, slots: editingSlots }
    });
    toast('success', 'Timing Saved', `Schedules for ${activeGroup} (${activeMode}) are now live.`);
  };

  const groups: ClassGroup[] = ['VI-X', 'XI-XII'];
  const modes: TimingMode[] = ['Official', 'Summer', 'Winter'];

  return (
    <div className="flex flex-col animate-fade">
      
      {/* Horizontal Selection Bar */}
      <div className="py-4 border-b border-slate-200 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-6">
          <div className="flex bg-slate-100 p-1 rounded-xl border border-slate-200">
            {groups.map(g => (
              <button 
                key={g}
                onClick={() => handleTabChange(g, activeMode)}
                className={`px-4 py-1.5 rounded-lg text-[0.65rem] font-black uppercase tracking-wider transition-all ${activeGroup === g ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}
              >
                Grade {g}
              </button>
            ))}
          </div>

          <div className="w-px h-6 bg-slate-200 hidden sm:block"></div>

          <div className="flex items-center gap-1.5">
            {modes.map(m => (
              <button 
                key={m}
                onClick={() => handleTabChange(activeGroup, m)}
                className={`px-3 py-1.5 rounded-lg text-[0.65rem] font-black uppercase tracking-widest transition-all ${activeMode === m ? 'text-slate-800 border-b-2 border-slate-800' : 'text-slate-400 hover:text-slate-600 border-b-2 border-transparent'}`}
              >
                {m}
              </button>
            ))}
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex gap-1 mr-2">
            <button onClick={() => shiftAll(-10)} className="h-8 w-10 flex items-center justify-center text-[0.65rem] font-black bg-white hover:bg-slate-50 text-slate-600 rounded-lg border border-slate-200 shadow-sm transition-all">-10</button>
            <button onClick={() => shiftAll(10)} className="h-8 w-10 flex items-center justify-center text-[0.65rem] font-black bg-white hover:bg-slate-50 text-slate-600 rounded-lg border border-slate-200 shadow-sm transition-all">+10</button>
          </div>
          
          <div className="h-6 w-px bg-slate-200 mx-1"></div>

          {/* Quick Print Button */}
          <button 
            className="h-9 px-4 bg-white border border-slate-200 rounded-xl flex items-center gap-2 text-[0.65rem] font-black text-slate-700 hover:bg-slate-50 transition-all shadow-sm active:scale-95"
            onClick={handlePrint}
          >
            <Printer size={14} className="text-rose-500" />
            Print Schedule
          </button>

          {/* Export Dropdown */}
          <div className="relative">
            <button 
              onClick={() => setShowExportMenu(!showExportMenu)}
              className="h-9 px-4 bg-white border border-slate-200 rounded-xl flex items-center gap-2 text-[0.65rem] font-black text-slate-700 hover:bg-slate-50 transition-all shadow-sm active:scale-95"
            >
              <Save size={14} className="text-indigo-500" />
              Save/Export
              <ChevronDown size={14} className={`text-slate-400 transition-transform ${showExportMenu ? 'rotate-180' : ''}`} />
            </button>

            {showExportMenu && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setShowExportMenu(false)}></div>
                <div className="absolute right-0 mt-2 w-56 bg-white/90 backdrop-blur-xl border border-slate-200 rounded-2xl shadow-2xl z-50 py-2 animate-in fade-in zoom-in duration-150 origin-top-right">
                  <div className="px-3 py-2 text-[0.55rem] font-black text-slate-400 uppercase tracking-widest border-b border-slate-50 mb-1">Documents</div>
                  <button onClick={handlePrint} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-700 hover:bg-rose-50 hover:text-rose-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-rose-50 flex items-center justify-center text-rose-500"><FileText size={14} /></div>
                    Portable PDF
                  </button>
                  <button onClick={() => toast('info', 'Exporting...', 'Preparing Excel matrix.')} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-700 hover:bg-emerald-50 hover:text-emerald-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-emerald-50 flex items-center justify-center text-emerald-500"><FileSpreadsheet size={14} /></div>
                    Excel Matrix
                  </button>
                  <button onClick={() => toast('info', 'Exporting...', 'Generating JPG graphic.')} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-700 hover:bg-amber-50 hover:text-amber-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-amber-50 flex items-center justify-center text-amber-500"><Image size={14} /></div>
                    JPG Graphic
                  </button>
                  
                  <div className="mx-3 my-2 border-t border-slate-50"></div>
                  <div className="px-3 py-2 text-[0.55rem] font-black text-slate-400 uppercase tracking-widest border-b border-slate-50 mb-1">Direct Share</div>
                  
                  <button onClick={() => handleShare('whatsapp')} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-700 hover:bg-green-50 hover:text-green-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-green-50 flex items-center justify-center text-green-500"><MessageCircle size={14} /></div>
                    Share via WhatsApp
                  </button>
                  <button onClick={() => handleShare('email')} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-700 hover:bg-blue-50 hover:text-blue-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-blue-50 flex items-center justify-center text-blue-500"><Mail size={14} /></div>
                    Share via Email
                  </button>
                  <button onClick={() => handleShare('clipboard')} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-700 hover:bg-indigo-50 hover:text-indigo-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-indigo-50 flex items-center justify-center text-indigo-500"><Share2 size={14} /></div>
                    Copy Formatted List
                  </button>
                  
                  <div className="mx-3 my-2 border-t border-slate-50"></div>
                  <button onClick={handleExportJSON} className="w-full flex items-center gap-3 px-4 py-2 text-xs font-bold text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors">
                    <div className="w-7 h-7 rounded-lg bg-slate-50 flex items-center justify-center text-slate-400"><Code size={14} /></div>
                    Internal Code JSON
                  </button>
                </div>
              </>
            )}
          </div>

          <button 
            className="px-4 py-1.5 text-[0.6rem] font-black text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-all uppercase tracking-widest shadow-sm"
            onClick={() => {
              localStorage.setItem('timetable_default_mode', activeMode);
              toast('success', 'Default Preset Saved', `${activeMode} schedule is now your global starting point.`);
            }}
          >
            Set As Default
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex flex-col min-w-0">
        <div className="py-4 flex items-center justify-between">
           <div className="flex items-center gap-2">
             <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></div>
             <h2 className="text-[0.65rem] font-black text-slate-800 uppercase tracking-widest">Active Timeline: {activeMode} ({activeGroup})</h2>
           </div>
        </div>

        <div className="flex flex-col gap-1.5 pb-24">
          {editingSlots.map((slot, index) => {
            const duration = getDuration(slot.startTime, slot.endTime);
            const isRecess = slot.isBreak;
            return (
              <div key={slot.id} className={`group px-5 py-3 rounded-2xl border transition-all duration-200 ${isRecess ? 'bg-rose-50/50 border-rose-100 shadow-sm' : 'bg-white border-slate-100 hover:border-indigo-200 hover:shadow-md'}`}>
                <div className="flex items-center gap-6">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border flex-shrink-0 transition-all ${isRecess ? 'bg-white border-rose-100 text-rose-500 shadow-inner' : 'bg-slate-50 border-slate-100 text-slate-400 group-hover:text-indigo-500 group-hover:bg-white'}`}>
                    {isRecess ? <Coffee size={16} /> : <span className="text-[0.7rem] font-black">{slot.name}</span>}
                  </div>
                  
                  <div className="flex-1 flex items-center gap-10">
                    <div className="min-w-[120px]">
                      <div className="text-[0.55rem] font-black text-slate-400 uppercase tracking-widest leading-none mb-1.5">{isRecess ? 'Recess Protocol' : 'Academic Span'}</div>
                      <div className="text-[0.75rem] font-bold text-slate-800">{isRecess ? 'General Break' : `Period ${slot.name}`}</div>
                    </div>

                    <div className="flex items-center gap-4">
                       <div className="relative">
                         <input 
                           type="time" 
                           className="text-base font-black text-slate-800 bg-transparent outline-none border-b-2 border-transparent focus:border-indigo-500 transition-colors cursor-pointer"
                           value={slot.startTime}
                           onChange={(e) => handleSlotChange(index, 'startTime', e.target.value)}
                         />
                       </div>
                       <ArrowRight size={14} className="text-slate-300" />
                       <div className="relative">
                         <input 
                           type="time" 
                           className="text-base font-black text-slate-800 bg-transparent outline-none border-b-2 border-transparent focus:border-indigo-500 transition-colors cursor-pointer"
                           value={slot.endTime}
                           onChange={(e) => handleSlotChange(index, 'endTime', e.target.value)}
                         />
                       </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-3">
                    <div className={`flex items-center bg-slate-100 rounded-lg px-2 py-1 ${duration < 0 ? 'bg-rose-100 border border-rose-200' : 'border border-slate-200'}`}>
                       <input 
                         type="number" 
                         className={`w-10 bg-transparent text-[0.65rem] font-black outline-none text-center ${duration < 0 ? 'text-rose-600' : 'text-slate-600'}`}
                         value={duration}
                         onChange={(e) => handleDurationChange(index, parseInt(e.target.value))}
                       />
                       <span className="text-[0.55rem] font-black text-slate-400 mr-1 uppercase">Min</span>
                    </div>
                    {duration < 0 && <Info size={16} className="text-rose-500 animate-pulse" />}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Floating Action Bar for De-nested view */}
        <div className="fixed bottom-8 right-8 z-50 flex items-center gap-4 bg-white/80 backdrop-blur-md p-2 rounded-2xl border border-slate-200 shadow-2xl animate-fade-in-up">
           <div className="pl-4 pr-6 text-[0.65rem] font-black text-slate-500 uppercase tracking-widest border-r border-slate-100 flex items-center gap-2">
             <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-pulse"></div>
             Live Propagation
           </div>
           <button 
             className="h-12 px-10 bg-indigo-600 text-white rounded-xl text-[0.7rem] font-black flex items-center gap-2 hover:bg-indigo-700 shadow-xl shadow-indigo-600/30 transition-all active:scale-95 uppercase tracking-widest"
             onClick={saveSettings}
           >
             <Save size={20} /> Deploy Schedule
           </button>
        </div>
      </div>
    </div>
  );
}
